"""add estado_venta to mensaje

Revision ID: 3108a8d88c0d
Revises: 6c439728a8c6
Create Date: 2025-05-24 17:34:38.641067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3108a8d88c0d'
down_revision: Union[str, None] = '6c439728a8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
