"""add creado_en to producto

Revision ID: 9f8ed68d3f4a
Revises: 
Create Date: 2025-05-21 19:43:01.352978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8ed68d3f4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('venta', sa.Column('producto_id', sa.Integer(), nullable=False))
    op.add_column('venta', sa.Column('cantidad', sa.Integer(), nullable=False))
    op.alter_column('venta', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('venta', 'detalle',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_venta_cliente_final_id'), table_name='venta')
    op.create_index(op.f('ix_venta_producto_id'), 'venta', ['producto_id'], unique=False)
    op.drop_constraint(op.f('venta_cliente_final_id_fkey'), 'venta', type_='foreignkey')
    op.drop_constraint(op.f('venta_mensaje_id_fkey'), 'venta', type_='foreignkey')
    op.create_foreign_key(None, 'venta', 'producto', ['producto_id'], ['id'])
    op.drop_column('venta', 'cliente_final_id')
    op.drop_column('venta', 'mensaje_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('mensaje_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venta', sa.Column('cliente_final_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venta', type_='foreignkey')
    op.create_foreign_key(op.f('venta_mensaje_id_fkey'), 'venta', 'mensaje', ['mensaje_id'], ['id'])
    op.create_foreign_key(op.f('venta_cliente_final_id_fkey'), 'venta', 'cliente_final', ['cliente_final_id'], ['id'])
    op.drop_index(op.f('ix_venta_producto_id'), table_name='venta')
    op.create_index(op.f('ix_venta_cliente_final_id'), 'venta', ['cliente_final_id'], unique=False)
    op.alter_column('venta', 'detalle',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('venta', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('venta', 'cantidad')
    op.drop_column('venta', 'producto_id')
    op.drop_column('producto', 'creado_en')
    # ### end Alembic commands ###
