"""add tipo_mensaje to mensaje

Revision ID: e6cff5e1d30b
Revises: 86b64bbb9b6a
Create Date: 2025-05-26 11:59:54.952438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cff5e1d30b'
down_revision: Union[str, None] = '86b64bbb9b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensaje', sa.Column('tipo_mensaje', sa.String(length=20), nullable=True))
    op.add_column('mensaje', sa.Column('metadatos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensaje', 'metadatos')
    op.drop_column('mensaje', 'tipo_mensaje')
    # ### end Alembic commands ###
