"""add logs table for auditoria

Revision ID: eb00271faaf1
Revises: 9f8ed68d3f4a
Create Date: 2025-05-21 21:00:04.190432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb00271faaf1'
down_revision: Union[str, None] = '9f8ed68d3f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('modelo', sa.String(length=50), nullable=False))
    op.add_column('logs', sa.Column('accion', sa.String(length=50), nullable=False))
    op.add_column('logs', sa.Column('detalle', sa.JSON(), nullable=False))
    op.alter_column('logs', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('logs', 'tipo')
    op.drop_column('logs', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('descripcion', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('logs', sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('logs', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('logs', 'detalle')
    op.drop_column('logs', 'accion')
    op.drop_column('logs', 'modelo')
    # ### end Alembic commands ###
