"""add chat_id to venta

Revision ID: fb8b13d16229
Revises: eb00271faaf1
Create Date: 2025-05-24 17:30:33.705729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb8b13d16229'
down_revision: Union[str, None] = 'eb00271faaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensaje_cliente_final_id'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_empresa_id'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_id'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_usuario_id'), table_name='mensaje')
    op.drop_table('mensaje')
    op.add_column('venta', sa.Column('chat_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_venta_chat_id'), 'venta', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_chat_id'), table_name='venta')
    op.drop_column('venta', 'chat_id')
    op.create_table('mensaje',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_final_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message_role', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('media_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vector_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_final_id'], ['cliente_final.id'], name=op.f('mensaje_cliente_final_id_fkey')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('mensaje_empresa_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('mensaje_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mensaje_pkey'))
    )
    op.create_index(op.f('ix_mensaje_usuario_id'), 'mensaje', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_mensaje_id'), 'mensaje', ['id'], unique=False)
    op.create_index(op.f('ix_mensaje_empresa_id'), 'mensaje', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_mensaje_cliente_final_id'), 'mensaje', ['cliente_final_id'], unique=False)
    # ### end Alembic commands ###
